MVVMにする、indicatorを実装する
yamanetaisei/cta_reactive_master pull request #11
Opened 2021-01-09 08:01 UTC by yamanetaisei

## 行ったこと
- [answerリポジトリ](https://github.com/CA21engineer/cta_reactive_master_answer)を参考にしてVMを定義

## 参考
- [answerリポジトリ](https://github.com/CA21engineer/cta_reactive_master_answer)

## その他 補足
-

2021-01-09 12:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewModel.swift
> +        output.showLoading.accept(false)
この falseを代入している箇所はarticleが取得し終わったときに行われていないので修正が必要そう

2021-01-09 12:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewModel.swift
> +    let indicator = UIActivityIndicatorView()
viewModelにindicatorを持たせるのはあんまり良くない
MVVM(View/ViewModel/Model)の場合明らかにViewに当たるものだから

2021-01-09 12:17 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewModel.swift
> +        let showLoading = BehaviorRelay<Bool>(value: true)
初期値はfalseにするべきだと思うで

2021-01-11 14:58 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewModel.swift
> +            .disposed(by: disposeBag)
言い忘れてしまった内容なんだけど
`init(dependency: Dependency) {}`を作成してその中にこれを移してほしい
この処理はfetch()の関数には直接的に関係してないので初期に読み込むべき内容でした:pray:

2021-01-11 14:58 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewModel.swift
> +        output.articles
これも言い忘れたものなんだけどこれの場合はerrorが起きた時にindicatorが止まらなくなってしまうので
したような感じに変更して欲しい:pray:
```
output.articles
　　　.flatMap { $0.error.map(Observable.just) ?? .empty() }
            .do(onNext: { [self] _ in
                output.showLoading.accept(false)
            })
            .subscribe()
            .disposed(by: disposeBag)
```

2021-01-19 13:41 UTC, takumaosada requested changes

2021-01-19 13:41 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewModel.swift
> +            .disposed(by: disposeBag)
`output.articles`を購読した中で`output.articles`を購読してるので意味ないので修正する必要がある！

2021-01-19 13:41 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewModel.swift
> +            .disposed(by: disposeBag)
こっちも

2021-01-20 01:24 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewModel.swift
> +            .disposed(by: disposeBag)
全く同じこと２回やってない？

2021-01-23 06:33 UTC, takumaosada requested changes
返事が遅くなって申し訳ないです:bow:

2021-01-23 06:33 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewModel.swift
> +            .disposed(by: disposeBag)
```suggestion
        output.articles
            .materialize()
            .do(onNext: { [self] _ in
                output.showLoading.accept(false)
            })
            .subscribe()
            .disposed(by: disposeBag)
```
これに省略できそうって話やね

2021-01-23 06:39 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewModel.swift
> +            .disposed(by: disposeBag)
ちなみにこう言う書き方もできる
ここら辺は好みの問題だと思う
```
        output.articles
            .materialize()
            .map { _ in false }
            .bind(to: output.showLoading)
            .disposed(by: disposeBag)
```

2021-01-23 06:40 UTC, takumaosada commented
今simulatorで確認したんだけどindicatorちゃんと表示されてないのでそれぞれの関数の実行タイミングをもう一回見直す必要がありそう

2021-01-23 09:03 UTC, yamanetaisei commented
おさたくさんのSuggested changeの通りに修正して、実行しました↓↓
うまく行ってるように見えるんですけど、なんか変ですか？？

<img src="https://user-images.githubusercontent.com/50735539/105573971-a0479e80-5da4-11eb-9232-b1e3e2440484.gif" width="300px">

2021-01-23 09:53 UTC, takumaosada commented
> おさたくさんのSuggested changeの通りに修正して、実行しました↓↓
> うまく行ってるように見えるんですけど、なんか変ですか？？
> 
> <img alt="" width="300px" src="https://user-images.githubusercontent.com/50735539/105573971-a0479e80-5da4-11eb-9232-b1e3e2440484.gif">

ほんまや
ごめん勘違いしてた:pray:

2021-01-23 09:53 UTC, takumaosada approved these changes

2021-01-23 09:54 UTC, yamanetaisei commented
よかった！！

2021-01-23 10:16 UTC, merged