tableViewに記事のタイトルを表示させる
yamanetaisei/cta_reactive_master pull request #6
Opened 2020-12-01 11:50 UTC by yamanetaisei

## 行ったこと
- データを受け取る構造体を記述
- 構造体の記述に沿った形でデータを取得
- データの"title"をtableViewに表示

<img src="https://user-images.githubusercontent.com/50735539/100736370-f5ef7280-3415-11eb-81a0-711dd3ce424e.PNG" width="220px">

## その他 補足
- Date型の表示の違いを吸収するために`decoder.dateDecodingStrategy = .iso8601`を記述しました
[参考](https://www.yoheim.net/blog.php?q=20180310)

## 質問
Decodableを継承した、structの記述でそれぞれのデータに型を指定する際にjsonのデータをみて、どうやって型を判断すればいいんですか？？
今回はテキトーに`String`とかを当てて、decodeに失敗したら`String?`とかにしてました。

2020-12-01 14:26 UTC, takumaosada requested changes

2020-12-01 14:26 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    var dataArray:[Articles] = [Articles]()
命名があんまり良くなさそうなので`articles`とかの方が良さそう

2020-12-01 14:26 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    var dataArray:[Articles] = [Articles]()
他のファイルで使ってないのでprivateつけることできる

2020-12-01 14:26 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        cell.textLabel?.text = dataArray[indexPath.row].title
カスタムセルとして定義している以上、`ArticleTableViewCell`にlabelを付与してそこに代入する方がいいと思う

2020-12-01 14:26 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        request.response { [self] response in
`[self]`ではなく`[weak self]`として定義した方がいい

2020-12-01 14:26 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +import Alamofire
viewControllerは扱いとしてはviewとしての意味合いが強いのでAPIを実際に叩いているのはviewController以外のclass(もしくはstruct)にしたい
なので`APIClient`というファイル及びクラスを作成してそこに`fetchArticles()`を含めて移動させてみて欲しい

2020-12-01 14:26 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +            self.articleTableView.reloadData()
`dataArray`に値が代入されなくても呼ばれてしまうので書く場所を変えた方がいいかも

2020-12-01 14:26 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        let decoder = JSONDecoder()
decoderはAPIが呼ばれるたびにinitializeされるのはよくないのでclass直下に定義した方がいい

2020-12-01 14:26 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        let request = AF.request("http://newsapi.org/v2/everything?q=bitcoin&from=2020-10-30&sortBy=publishedAt&apiKey=30d06e4f9a934402a204fa89f9d9acfc")
`APIClient`のファイル作成するときに
- `everything?q=bitcoin&from=2020-10-30&sortBy=publishedAt`が色々なパターンがあるはずだからそれを入れ替えられる考慮を最低限する
- APIKEYをベタがきしない
あたりを考えながら少し挑戦してみて欲しいかも
https://dev.classmethod.jp/articles/webapi_client_not_use_liblary_swift/

2020-12-01 14:26 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        cell.textLabel?.text = dataArray[indexPath.row].title
画像とか、作成者とか他の情報も追加できそうであれば追加して欲しい

2020-12-01 14:26 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
>              articleTableView.register(UINib(nibName: "ArticleTableViewCell", bundle: nil), forCellReuseIdentifier: "ArticleTableViewCell")
前回多分見逃してしまったんだけどtableViewは`articleTableView`みたいな〇〇tableViewという命名にはせず、普通に`tableView`として命名するのが一般的。

2020-12-02 01:49 UTC, ry-itto commented on CtaReactiveMaster/Sources/Home/NewsDataModel.swift
> +}
この構造体一つ単位だと単一の記事だと思うので、名前を単数形にしよう

2020-12-08 14:42 UTC, yamanetaisei commented
make setupしたのち、make updateをしました、多分Nukeのバージョンが変わったような気がします

2020-12-12 14:33 UTC, takumaosada requested changes
> tableViewを更新する際に、apiClient.fetchArticles() を呼び出していて、tableViewを初期化するときの処理とほとんど変わらない処理を記述していることに納得いってないです。

そもそもpull-to-refreshという機能自体が`apiClient.fetchArticles() を呼び出していて、tableViewを初期化するときの処理`のことを指すのでその認識で問題ない。ここで大事なのはソレをユーザー自身の意思(タイミング)で使えるかどうかという点にある

2020-12-12 14:33 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    private let refreshCtl = UIRefreshControl()
`refreshCtl` として略すのはごく稀に見るけど一般的ではないので`refreshControl`の方がいいかも

2020-12-12 14:33 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +            refreshCtl.addTarget(self, action: #selector(HomeViewController.refresh(sender:)), for: .valueChanged)
これはrxを使わない場合に使う方法なのでこの処理をrxで書いてもらわないと今回の課題を満たせない

2020-12-12 14:36 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +    @objc func refresh(sender: UIRefreshControl) {
```suggestion
    @objc 
    func refresh(sender: UIRefreshControl) {
```
ここ改行あるといいかも

2020-12-12 14:36 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        print("くるくる")
消した方がいいかも

2020-12-12 15:46 UTC, yamanetaisei commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        print("くるくる")
動作確認の時に出力してたやつを消し忘れました><

2020-12-14 16:24 UTC, takumaosada reviewed
rxのところいい感じ！コメントしたところとrepositoryのやつやってもらえれば良さそう！

2020-12-14 16:24 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +            .disposed(by: disposeBag)
ここ`fetch()`にしちゃえば良さそう(`endRefreshing()`をいい感じにハンドリングして欲しい)

2020-12-14 16:24 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/APIClient.swift
> +
このスペース気になる

2020-12-14 16:24 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +        cell.textLabel?.text = articles[indexPath.row].title
画像周りは別のPRでいいけどlabelをxib上に定義して使うのはこのPR内でやって欲しいかも

2020-12-16 09:59 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +                if ((self?.refreshControl.isRefreshing) != nil){
`self?.refreshControl.isRefreshing) != nil`はself(ここではHomeViewController)に対して判断してるので`isRefreshing`がtrueかfalseなのかは見てないけど大丈夫そう？

2020-12-27 05:13 UTC, takumaosada reviewed
みた！あと少しだけなのでそれ修正してもらえると！

2020-12-27 05:13 UTC, takumaosada commented on CtaReactiveMaster/Resources/Info.plist
> +	</dict>
これ必要ない可能性高そうなので消して再度確認して欲しいかも

2020-12-27 05:13 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/HomeViewController.swift
> +import Alamofire
このimport文もういらなくなってるはず

2020-12-27 05:13 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/NewsAPIRequest.swift
> +    }
ちなみに`APIKey.plist`を使わなくてもこれでも全然問題ない
ただこの書き方の場合はこれだけでいいはず
```suggestion
    static let newsApi = "30d06e4f9a934402a204fa89f9d9acfc"
```

2020-12-27 05:26 UTC, takumaosada commented on CtaReactiveMaster/Sources/Home/NewsAPIRequest.swift
> +    }
ごめん、このレポジトリpublicだから不正利用される可能性高いのでやっぱり`APIKey.plist`での対応でお願いします:bow:

2020-12-27 14:56 UTC, yamanetaisei commented
APIKey.plistのignoreは[この記事](https://qiita.com/yutosa3/items/25ab031c8061e8c9a4c4) を参考にしました

2020-12-27 15:26 UTC, takumaosada approved these changes
LGTM！

2020-12-28 02:26 UTC, merged